public with sharing class ParametersDataTable {
    public String estatusNoOrdinario { get; set; }
    public List<String> clavesSeleccionadas { get; set; }
    public List<String> umusSeleccionadas { get; set; }
    public List<String> estadosSeleccionados { get; set; }
    public List<String> pedidosSeleccionados { get; set; }
    public List<String> transportesSeleccionados { get; set; }
    public Date fechaInicio { get; set; }
    public Date fechaFin { get; set; }
}